# Generated by Django 3.2.15 on 2023-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uavModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('weight', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
