# Generated by Django 3.2.15 on 2023-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
